version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/kits/Inertia/Blank/Base/.github/workflows"
      - "/kits/Livewire/Blank/.github/workflows"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
